### ISSUE TITLE
yield* cashed(maxAge) - maxAge is not sent to set()

### ISSUE THREAD

**Issue by mull** [koajs/cash#1]
Hi!

[According to the docs](https://github.com/koajs/cash#var-cached--yield-thiscashedmaxage) I should be able to pass `maxAge` to `yield* cashed(maxAge)`. However this does not seem to be the case, as my get function receives only two values.

**Comment by jonathanong** [comment]
can you provide a test case? i'm not sure what you mean

**Comment by eknkc** [comment]
I believe he says that it should be sent to `set` function too (as per the issue title). I'd like to see that too.
It would make things much better if the `set` function signature was `set(key, value, maxAge)` so when I'm using redis with this, I can just send the appropriate ttl value to redis.

**Comment by eknkc** [comment]
Something in line with this: https://github.com/eknkc/cash/commit/6baa22122e320cc1c0f5f0dcaf8ce8a7a813c48a

Sorry, I just edited this on GitHub's web interface, have no means to test it right now so it's just for reference. I'd have sent a PR otherwise.

**Comment by jonathanong** [comment]
ah it's a feature request. got it.

**Comment by mull** [comment]
Hey, sorry for the radio silence. I accidentally deleted the email. Pretty sure I somehow got the idea that this should already happen from reading the docs. Anyhow, thanks for implementing it - I think it's a much needed future going forward. :)
