### ISSUE TITLE
Supporting request method POST

### ISSUE THREAD

**Issue by spanitz** [koajs/cash#2]
Any chance to support POST or the ability to configure supported methods with options?

I could do a PR, if you add me as a contributor.

**Comment by jonathanong** [comment]
what's the use-case here?

**Comment by spanitz** [comment]
It would offer the ability to cache the response body of non-restful POST request.

**Comment by jonathanong** [comment]
i don't understand the use-case, but i don't mind removing the method restrictions because the user can do that themselves.

**Comment by caiquecastro** [comment]
It does not make sense for me. Can you cache some heavy computation somewhere else?
